---
title: "The Natural History of Hypertension in Older Adults: A Study of Two Finnish Generational Cohorts Born 20 Years Apart - count missing data"
output: html_document
date: "2023-10-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages

# First pacman
library(pacman)

# Load the rest
p_load(ggplot2, ggthemes, dplyr, knitr, kableExtra, janitor, flextable, tidyr, here)

# Load the datasets with the {here} package

# Tell the "here" package where you are right now - i.e. tell the location of the file you are running right now

here::i_am("article1/count_missing_data_filled.Rmd")

# After that, you can check where the project root is by running "here()"
here()


#  Load the datasets using {here} package
article1tuva_file <- here("data", "tuva.rds")
article1utuva_file <- here("data", "utuva.rds")

article1tuva <- readRDS(article1tuva_file)
article1utuva <- readRDS(article1utuva_file)

# Clean up variables
rm(article1tuva_file, article1utuva_file)

#article1tuva <- readRDS("~/the_a_team/data/tuva.rds")
#article1utuva <- readRDS("~/the_a_team/data/utuva.rds")
```

## Missing Data UTUVA
```{r}
#UTUVA 70
utuva70miss <- article1utuva %>% select(ID1991, ID2011, B8_3_PVM_U70, B8_3_A7isys_U70)

utuva70miss$B8_3_PVM_U70 <- na_if(article1utuva$B8_3_PVM_U70, "")
#utuva70miss$B8_3_A7isys_U70 <- na_if(article1utuva$B8_3_A7isys_U70, "")

# Drop all cases who don't have the study date
utuva70miss <- utuva70miss %>% drop_na(B8_3_PVM_U70)

utuva70miss %>%
  summarise(Variable = "Systolic BP in UTUVA70",
            `Total N` = n(),
            Missing = sum(is.na(B8_3_A7isys_U70)),
            `Missing (%)` = Missing/`Total N`*100)

# Store that:
utuva70miss_table <- 
  utuva70miss %>%
  summarise(Variable = "Systolic BP in UTUVA70",
            `Total N` = n(),
            Missing = sum(is.na(B8_3_A7isys_U70)),
            `Missing (%)` = round_half_up((Missing/`Total N`*100),1))
```



```{r}
"UTUVA 75"
utuva75miss <- article1utuva %>% select(ID1991,ID2011, B10b_c_U75, B10b_A7_2_1_U75)

# Drop all cases who don't have the study date
utuva75miss <- utuva75miss %>% drop_na(B10b_c_U75)

nrow(utuva75miss)

utuva75miss %>% filter(is.na(B10b_A7_2_1_U75)) %>% nrow()

round_half_up(12 / 707 * 100, 2)

# Store that:
utuva75miss_table <- 
  utuva75miss %>%
  summarise(Variable = "Systolic BP in UTUVA75",
            `Total N` = n(),
            Missing = sum(is.na(B10b_A7_2_1_U75)),
            `Missing (%)` = round_half_up(Missing/`Total N`*100, 1))


"UTUVA 80"
# Retain only the study date and SBP, discard rest
utuva80miss <- article1utuva %>% select(ID1991, ID2011, tutk_pvm, RR_syst_istuen_U80)

# "tutk_pvm" does not contain NA but rather "" for missing data
# Same thing with "RR_syst_istuen_U80"!
# Fix those issues
utuva80miss$tutk_pvm <- na_if(utuva80miss$tutk_pvm, "")
utuva80miss$RR_syst_istuen_U80 <- na_if(utuva80miss$RR_syst_istuen_U80, "")

# Drop all cases who don't have the study date
utuva80miss <- utuva80miss %>% drop_na(tutk_pvm)

# Count the missing data
utuva80miss %>%
  summarise(Variable = "Systolic BP in UTUVA80",
            `Total N` = n(),
            Missing = sum(is.na(RR_syst_istuen_U80)),
            `Missing (%)` = Missing/`Total N`*100)

# Store that:
utuva80miss_table <- 
  utuva80miss %>%
  summarise(Variable = "Systolic BP in UTUVA80",
            `Total N` = n(),
            Missing = sum(is.na(RR_syst_istuen_U80)),
            `Missing (%)` = round_half_up((Missing/`Total N`*100),1))

```

## TUVA70

```{r}
"TUVA 70"
tuva70miss <- article1tuva %>% select(ID1991,ID2011, PAIVAMA_70_PVM, SRR_70_istuen)

# Drop all cases who don't have the study date
tuva70miss <- tuva70miss %>% drop_na(PAIVAMA_70_PVM)

nrow(tuva70miss)

tuva70miss %>% filter(is.na(SRR_70_istuen)) %>% nrow()

tuva70miss %>%
  summarise(Variable = "Systolic BP in TUVA70",
            `Total N` = n(),
            Missing = sum(is.na(SRR_70_istuen)),
            `Missing (%)` = Missing/`Total N`*100)

# Store that:
tuva70miss_table <- 
  tuva70miss %>%
  summarise(Variable = "Systolic BP in TUVA70",
            `Total N` = n(),
            Missing = sum(is.na(SRR_70_istuen)),
            `Missing (%)` = round_half_up(Missing/`Total N`*100, 1))
```
## TUVA80

```{r}
"TUVA 80"
tuva80miss <- article1tuva %>% select(ID1991,ID2011, PAIVAMA_PVM_80, SRR_80_istuen)

tuva80miss <- tuva80miss %>% drop_na(PAIVAMA_PVM_80)

nrow(tuva80miss)

tuva80miss %>% filter(is.na(SRR_80_istuen)) %>% nrow()

tuva80miss %>%
  summarise(Variable = "Systolic BP in TUVA80",
            `Total N` = n(),
            Missing = sum(is.na(SRR_80_istuen)),
            `Missing (%)` = Missing/`Total N`*100)

# Store that:
tuva80miss_table <- 
  tuva80miss %>%
  summarise(Variable = "Systolic BP in TUVA80",
            `Total N` = n(),
            Missing = sum(is.na(SRR_80_istuen)),
            `Missing (%)` = round_half_up(Missing/`Total N`*100, 1))
```

##TUVA85

```{r}
"TUVA 85"
tuva85miss <- article1tuva %>% select(ID1991,ID2011, PAIVAMA_PVM_85, SRR_istuen_85)

tuva85miss <- tuva85miss %>% drop_na(PAIVAMA_PVM_85)

nrow(tuva85miss)

tuva85miss %>% filter(is.na(SRR_istuen_85)) %>% nrow()

tuva85miss %>%
  summarise(Variable = "Systolic BP in TUVA85",
            `Total N` = n(),
            Missing = sum(is.na(SRR_istuen_85)),
            `Missing (%)` = Missing/`Total N`*100)

# Store that:
tuva85miss_table <- 
  tuva85miss %>%
  summarise(Variable = "Systolic BP in TUVA85",
            `Total N` = n(),
            Missing = sum(is.na(SRR_istuen_85)),
            `Missing (%)` = round_half_up(Missing/`Total N`*100, 1))
```

##TUVA90

```{r}
"TUVA 90"
tuva90miss <- article1tuva %>% select(ID1991, ID2011, Tutkimuspaivamaara_F90, SRR_90_istuen)

tuva90miss$Tutkimuspaivamaara_F90 <- na_if(tuva90miss$Tutkimuspaivamaara_F90, "")
#tuva90miss$SRR_90_istuen <- na_if(tuva90miss$SRR_90_istuen, "")

tuva90miss <- tuva90miss %>% drop_na(Tutkimuspaivamaara_F90)

tuva90miss %>%
  summarise(Variable = "Systolic BP in TUVA90",
            `Total N` = n(),
            Missing = sum(is.na(SRR_90_istuen)),
            `Missing (%)` = Missing/`Total N`*100)

# Store that:
tuva90miss_table <- 
  tuva90miss %>%
  summarise(Variable = "Systolic BP in TUVA90",
            `Total N` = n(),
            Missing = sum(is.na(SRR_90_istuen)),
            `Missing (%)` = round_half_up(Missing/`Total N`*100, 1))

```

##TUVA95

```{r}
"TUVA 95"
tuva95miss <- article1tuva %>% select(ID1991, ID2011, PAIVAMAA_95, FYSMIT6b2a)

tuva95miss$PAIVAMAA_95 <- na_if(tuva95miss$PAIVAMAA_95, "")
tuva95miss$FYSMIT6b2a <- na_if(tuva95miss$FYSMIT6b2a, "")

tuva95miss <- tuva95miss %>% drop_na(PAIVAMAA_95)

tuva95miss %>%
  summarise(Variable = "Systolic BP in TUVA95",
            `Total N` = n(),
            Missing = sum(is.na(FYSMIT6b2a)),
            `Missing (%)` = Missing/`Total N`*100)

# Store that:
tuva95miss_table <- 
  tuva95miss %>%
  summarise(Variable = "Systolic BP in TUVA95",
            `Total N` = n(),
            Missing = sum(is.na(FYSMIT6b2a)),
            `Missing (%)` = round_half_up(Missing/`Total N`*100, 1))

```

## Combined tables

```{r}
############################################################################
############################################################################
###                                                                      ###
###                          COMBINE THE TABLES                          ###
###                                                                      ###
############################################################################
############################################################################


# Combine those 2 tables
utuva_ctable <- rbind(utuva70miss_table, utuva75miss_table, utuva80miss_table)



# Convert the tibble to a flextable object
ft <- flextable(utuva_ctable)
ft <- align(ft, j = 2, align = "center", part = "all")
ft <- ft %>% bold(part = "header", bold = TRUE)
ft <- ft %>% add_header_lines("Supplementary Table S1. Missing data for blood pressure variables in each time point of the study.")
ft <- set_table_properties(ft, width = 1, layout = "autofit")

# Display the flextable
ft

# Export as docx
save_as_docx(ft, path = "Supplementary_Table_S1.docx")
```
```{r}
tuva_ctable <- rbind(tuva70miss_table, tuva80miss_table, tuva85miss_table, tuva90miss_table, tuva95miss_table)

ft <- flextable(tuva_ctable)
ft <- align(ft, j = 2, align = "center", part = "all")
ft <- ft %>% bold(part = "header", bold = TRUE)
ft <- ft %>% add_header_lines("Supplementary Table S2. Missing data for blood pressure variables in each time point of the study.")
ft <- set_table_properties(ft, width = 1, layout = "autofit")

# Display the flextable
ft

# Export as docx
save_as_docx(ft, path = "Supplementary_Table_S2.docx")
```

